zhoumo01/ulearning-asia

- locales/templates/templates_zh.properties
> 新增app端登录提示语待翻译字段

- locales/templates/手机考试zh.json
> 新增了手机考试-考试激活的字段

- locales/templates/2.0_admin.js.json
- locales/templates/2.0_classroom.js.json
- locales/templates/2.0_course.js.json
- locales/templates/2.0_public.js.json
> 更新了中航一起的一些翻译字段

- locales/templates/2.0_admin.js.json
> 更新了马来西亚的项目的一个字段

- locales/templates/1.0_questionIndex2.js.json
> 题库复制需求新增字段

- locales/templates/2.0_classroom.js.json
- locales/templates/2.0_course.js.json
- locales/templates/2.0_public.js.json
> 添加国际化语言字段信息

- locales/templates/2.0_admin.js.json
- locales/templates/2.0_classroom.js.json
- locales/templates/2.0_course.js.json
> course_web 新增中航翻译字段

- locales/templates/2.0_aboutUs.js.json
- locales/templates/2.0_admin.js.json
> course admin 新增翻译

- locales/templates/2.0_course.js.json
> course_web 新增lti的字段

- locales/templates/utest_api_zh.properties
> utest后端翻译文件

- locales/templates/exam_web.json
> 题库重构前端翻译字段

- locales/templates/exam_web.json
> 新版题库翻译补充字段1.0

- locales/templates/exam_web.json
> 禁止跳题字段+考试优化字段

- locales/templates/2.0_exam.js.json
> 禁止跳题字段+重新评分字段

- locales/templates/2.0_exam.js.json
> 禁止跳题漏翻字段+重新评分字段

- locales/templates/2.0_exam.js.json
> 重新评分需求字段更新

- locales/templates/2.0_exam.js.json
- locales/templates/exam_web.json
- locales/templates/手机考试zh.json
> 网络异常提示优化字段

- locales/templates/apps.json
- locales/templates/smartClass.json
> 智慧课堂移动端新增翻译字段

- locales/templates/apps.json
- locales/templates/smartClass.json
> 课堂支持老师上传图片字段翻译

- locales/templates/ua_zh.js.json
"videoAddress": "视频地址",  此字段翻译错误
并新增两处翻译字段，
> youtube的Placeholder字段

- locales/templates/2.0_public.js.json
- locales/templates/admin2.json
> 租户添加机构术语以及旧管理切换按钮

- locales/templates/exam_web.json
> 网页唤醒锁屏客户端新增翻译

- locales/templates/2.0_exam.js.json
- locales/templates/paper-export.json
> 答题记录导出紧凑版-字段翻译

- locales/templates/2.0_public.js.json
- locales/templates/apps.json
> 补充和部分修改翻译字段

- locales/templates/2.0_public.js.json
- locales/templates/tvet-portal.json
> 新增职教门户翻译文件

- locales/templates/2.0_admin.js.json
- locales/templates/2.0_public.js.json
> 【首次登录】补充翻译

- locales/templates/2.0_admin.js.json
> 【LTI】补充校验字段

- locales/templates/tvet-portal.json
> 【职教门户】翻译调整及补充

- locales/templates/2.0_course.js.json
- locales/templates/2.0_index.js.json
> course_web导入CC字段更新

- locales/templates/groupwork.json
> 新版小组作业【移动端】

- locales/templates/discussion_international.json
- locales/templates/groupwork.json
> 新版讨论、新版小组作业遗留字段

- locales/templates/2.0_exam.js.json
- locales/templates/exam_web.json
- locales/templates/手机考试zh.json
> 考试PC端部分翻译字段

- locales/templates/smartClass.json
> 智慧课堂部分翻译字段

- locales/templates/apps.json
> app课堂添加部分翻译

- locales/templates/ua_zh.js.json
> ua_web中文字段

- locales/templates/2.0_course.js.json
> course_web分章节导入中文字段

- locales/templates/2.0_course.js.json
- locales/templates/2.0_reponsitory.js.json
> course_web资源库-上传文件夹更新
